const express = require("express");
const router = express.Router();
const { recipesController } = require("../controller/recipes");
const upload2 = require("../middlewares/upload");
const upload = require("../middlewares/upload-video");
const { user } = require("../middlewares/user");

router.post("/", upload, user, recipesController.insert);
router.post("/comments/:id", user, recipesController.addComents);
router.post("/save/", user, recipesController.addBookmark);
router.put("/update/:id", upload, recipesController.update);
router.delete("/delete/:id", recipesController.delete);
router.get("/detail/:id", recipesController.detail);
router.get("/user-recipes/", user, recipesController.recipeUSer);
router.get("/search", recipesController.sort);
router.get("/save", user, recipesController.getBookmark);
router.delete("/save/:id", recipesController.deleteBookmark);
router.get("/comments/:id", recipesController.getComment);
router.post("/liked", user, recipesController.addLike);
router.get("/liked", user, recipesController.getLiked);
router.delete("/liked/:id", recipesController.deleteLike);
module.exports = router;
